### ISSUE TITLE
Use fitted OUwie object for simulation

### ISSUE THREAD

**Issue by bomeara** [thej022214/OUwie#1]
Rather than rely on users extracting parameters to use for simulation, let them pass in a fitted object and do it internally.

**Comment by bomeara** [comment]
Implemented (I think) for all models but OU1 and BM1. Need to do those more. Also, measurement error isn't incorporated yet

**Comment by willgearty** [comment]
I had been working on similar code [here](https://bitbucket.org/wgearty/body-size-analyses/src/68e75dc1907caf05adb40c45a58d37ccaf4102d8/Mammals/OUwie.boot.parse.R?fileviewer=file-view-default). Feel free to use any or all of it.
