### ISSUE TITLE
Estimate Errors

### ISSUE THREAD

**Issue by C-G-L** [thej022214/OUwie#10]
Hi, I am running OUwie on the anole dataset and walking through the tutorial found here (http://www.phytools.org/Cordoba2017/ex/10/Multi-regime.html). When i perform the fitOUM step, the library i have installed returns an estimate astronomically different from the one presented in the tutorial. What could be the reason for this?

**Comment by thej022214** [comment]
Well, given it is based on a simmap the results will be slightly different. However, there was a bug in the way in which the weight matrix was being generated that we recently fixed as well as how what we assume at the root (see new vignette), and we've also been working on improving the way the optimization is carried out given the common failures of the OUMA and OUMVA models.

**Comment by C-G-L** [comment]
Thank you! I solved the issue by updating the Ouwie.rdb and restarting the r session. Thank you for getting back so soon!
