### ISSUE TITLE
Fixed lower and upper bound in OUwie search

### ISSUE THREAD

**Issue by Caetanods** [thej022214/OUwie#12]
_Minor detail that does not influence the method performance._
Hey @jboyko ! The lower and upper bounds are fixed for `Ouwie`. The current code in the branch has the `lb` and `up` arguments, but these arguments are not in the call for the function in the RCran version 2.5 . If you try to specify the bounds using the `opts` argument, it will not be passed to `nloptr`.

**Comment by jboyko** [comment]
I believe this is fixed on the latest version! It will be released to the masses shortly.

User input first enters code:
https://github.com/thej022214/OUwie/blob/3339416fa3436185fdbe81a61f017ce388fc7d68/R/OUwie.R#L432
*~* some modifications *~*
User input enters nloptr:
https://github.com/thej022214/OUwie/blob/3339416fa3436185fdbe81a61f017ce388fc7d68/R/OUwie.R#L497

**Comment by Caetanods** [comment]
Awesome! Thanks.
