### ISSUE TITLE
Strange estimates when using get.root.theta

### ISSUE THREAD

**Issue by soungalo** [thej022214/OUwie#16]
```
OUwie(tree, data, model=c('OU1'))

Fit
       lnL      AIC     AICc      BIC model ntax
 -37.17996 80.35992 80.63264 87.92528   OU1   92


Rates
     alpha   sigma.sq 
0.01166031 0.00591319 

Optima
                 1
estimate 6.2020929
se       0.1171128


Half life (another way of reporting alpha)
   alpha 
59.44498 

Arrived at a reliable solution
```

```
OUwie(tree, data, model=c('OU1'), get.root.theta=TRUE)

Fit
       lnL      AIC     AICc     BIC model ntax
 -36.66562 81.33124 81.79101 91.4184   OU1   92


Rates
      alpha    sigma.sq 
0.010072403 0.005414692 

Optima
            root         1
estimate 6776578 -53271.15
se       6414863  50433.58


Half life (another way of reporting alpha)
   alpha 
68.81647 

Arrived at a reliable solution
``` 

Why are the estimates so different? They don't make much sense in the second case. Is there anything that can be done?
I can provide the actual data if that's relevant.

Thanks!

**Comment by jboyko** [comment]
Hello!

I believe that this is the result of the model being unidentifiable when root.theta is estimated (See Figure 5 here: https://www.biorxiv.org/content/10.1101/2023.01.10.523430v1.full.pdf+html). The model being unidentifiable (or at least practically unidentifiable) is reflected in the massive standard error estimates in the second model. I would exclude the second model from any downstream analysis. Unfortunately, there is likely little else that can be done about this at the moment. 

Also see: Ho, L. S. T., and C. Ané. 2014. Intrinsic inference difficulties for trait evolution with Ornstein‐Uhlenbeck models. Methods in Ecology and Evolution 5:1133–1146.

Best,
James

**Comment by soungalo** [comment]
Thank you.
