### ISSUE TITLE
OUM, out of bounds

### ISSUE THREAD

**Issue by ghost** [thej022214/OUwie#2]
Hi,
I am facing an issue when using the model OUM, producing the following error:
```
Error in `[<-`(`*tmp*`, , 7:(k + 5), value = 0) : subscript out of bounds
```
when I choose to use a regime for the root that differs from present regime, i.e.

```
   |---A
A--|---B
   |---C
```

works fine

```
   |---A
R--|---B
   |---C
```
crashes

Note that the model BM1,BMS,OU1, and OUMV can cope with this situation. Since it is a crash and not a proper warning or error, I not sure whether this is a misuse from me, or an actual bug. Any clue?

v1.51

Best

**Comment by thej022214** [comment]
Can you email me privately with your data set and tree so I can take a closer look. jmbeauli@uark.edu.

It sounds like a bug, but I  can't be sure (I haven't worked on this for quite some time).

Best.
