### ISSUE TITLE
OUwie currently incorrectly obtains a gibberish root age if passed a non-ultrametric tree without a root age from user

### ISSUE THREAD

**Issue by dwbapst** [thej022214/OUwie#3]
Hello,

A recent issue raised on R-Sig-Phylo has revealed that if a root age is not given for the user-supplied tree, then a root age is instead obtained by calling `max(branching.times(tree))` Apparently in some circumstances, this results in a negative estimate of the root age, and a confusing warning from the paleotree function, which is right to be utterly confused.

https://github.com/thej022214/OUwie/blob/dbce6a65b630734fcd74201b38e8a50fd7503186/R/OUwie.R#L682-L695

Unfortunately, `branching.times` returns gibberish when applied to non-ultrametric trees.  As noted in Emmanuel's documentation for `branching.times`:

>This function computes the branching times of a phylogenetic tree, that is the distance from each node to the tips, under the assumption that the tree is ultrametric. Note that the function does not check that the tree is effectively ultrametric, so if it is not, the returned result may not be meaningful.

Literally, it arbitrarily picks a tip, and measures the distance from the root to the other tips relative to that distance. Unless it luckily picks the tip furthest (in time) from the root on a non-ultrametric tree, its just gibberish, and often has negative values.

This same issue came up in geiger, where branching times was used to get tree depths for the Early Burst model, which meant the model was being incorrectly parameterized for non-ultrametric trees:

https://github.com/mwpennell/geiger-v2/issues/20

The correct solution here, as with that issue, is to simply replace `branching.times` with a call to `node.depth.edgelength`, which will return a vector where the `max` will always be the distance from the root to the furthest tip.

Cheers,
-Dave Bapst

**Comment by dwbapst** [comment]
Is this issue really still open?

**Comment by thej022214** [comment]
Yes. And I am closing it.

**Comment by dwbapst** [comment]
So you fixed it?

**Comment by thej022214** [comment]
Yes, hence the closing.


-------------------------------
Jeremy M. Beaulieu
Assistant Professor
Biological Sciences
University of Arkansas
(479) 575-2618
www.jeremybeaulieu.org<http://www.jeremybeaulieu.org>
eeob.uark.edu<https://eeob.uark.edu>

On Apr 21, 2020, at 2:56 PM, David Bapst <notifications@github.com<mailto:notifications@github.com>> wrote:



So you fixed it?
