### ISSUE TITLE
Error in cbind(edges, regime) :    number of rows of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by coyotree** [thej022214/OUwie#5]
Hello,

I am using OUwie to look at the relationship between a binary character and a continuous trait. I have successfully executed OUwie using output from BAYOU; however, now trying to use my raw continuous data rather than the BAYOU regimes, I cannot seem to manage. 

I have my data set up the same as the example OUwie data set as far as I can tell. The rows are ordered by the tree tip order. I even renamed and reordered the columns to match the example data set. However, I keep getting the same error of:
```
> ssw.oumva <- OUwie(all.hind.tree, all.hind.mean.sorted, model = "OUMVA", simmap.tree = F, diagn = T)
Error in cbind(edges, regime) : 
  number of rows of matrices must match (see arg 2)
```
The number of rows match the number of tips. The OU1 model works but none of the others do.

```
> all.hind.tree
Phylogenetic tree with 62 tips and 61 internal nodes.
Tip labels:
	Onc...
Rooted; includes branch lengths.

> nrow(all.hind.mean.sorted)
[1] 62
```
I'm using OUwie v. 1.50; R version 3.5.2

Any advice appreciated. This is probably some newbie mistake on my end.

Thanks,
Cody Coyotee

**Comment by thej022214** [comment]
It looks like you are inputting a tree that does contain regimes information on internal nodes.

**Comment by coyotree** [comment]
Yes, that was the problem. May this closed ticket serve as a guide to all those who make the same oopsie.
